### ISSUE TITLE
indrop v3

### ISSUE THREAD

**Issue by Jachimdejonghe** [biocorecrg/indrop#6]
Hello,

 Thank you for making this available. I was wondering if the pipeline would be made available for indrop v3 libraries?

Thanks alot

**Comment by lucacozzuto** [comment]
Hi, if you have some test dataset we can think to add this possibility.

**Comment by Jachimdejonghe** [comment]
Ah yes I would gladly send some datasets over,  I will DM you with the specifics

**Comment by lucacozzuto** [comment]
Nice!
